# Generated by Django 4.0.6 on 2022-07-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Loyiha rasmi:')),
                ('project_name', models.CharField(max_length=30, verbose_name='Loyiha nomiL:')),
                ('project_description', models.TextField(verbose_name='Loyiha haqida qisqacha:')),
                ('project_tech', models.TextField(verbose_name='Loyiha uchun ishlatilgan texnalogiyalar:')),
                ('project_view', models.TextField(verbose_name='Demo sayt manzili:')),
            ],
            options={
                'verbose_name': 'Portfolio',
            },
        ),
    ]
