# Generated by Django 4.0.6 on 2022-08-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='project_github',
            field=models.TextField(default=' ', verbose_name="GitHub'dagi linki:"),
            preserve_default=False,
        ),
    ]
