# Generated by Django 4.0.6 on 2022-09-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_works_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='project_tech',
        ),
        migrations.AddField(
            model_name='works',
            name='project_direction',
            field=models.CharField(choices=[('1', 'Barchasi'), ('2', 'Frontend'), ('3', 'Backend'), ('4', 'Telegram bot')], default=0, max_length=35, verbose_name="Loyiha yo'nalishi:"),
        ),
        migrations.AlterField(
            model_name='works',
            name='project_name',
            field=models.CharField(max_length=30, verbose_name='Loyiha nomi:'),
        ),
    ]
