# Generated by Django 4.0.6 on 2022-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_works_project_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='project_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
