# Generated by Django 4.0.6 on 2022-09-08 08:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_works_project_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='project_client',
            field=models.CharField(max_length=30, null=True, verbose_name='Client ism:'),
        ),
        migrations.AlterField(
            model_name='works',
            name='project_description',
            field=ckeditor.fields.RichTextField(verbose_name='Loyiha haqida(Batafsil):'),
        ),
    ]
