# Generated by Django 4.0.6 on 2022-10-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_works_project_client_alter_works_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasmni kiriting:')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='works',
            name='project_name',
            field=models.CharField(max_length=50, verbose_name='Loyiha nomi:'),
        ),
    ]
