# Generated by Django 4.0.6 on 2022-11-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_home_alter_works_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Rasmni kiriting:'),
        ),
    ]
