# Generated by Django 4.0.6 on 2022-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_view',
            field=models.IntegerField(default=0),
        ),
    ]
